name: flask_rest_env
dependencies:
  - pip
  - python=3.7
  - pip:
    - Flask-Migrate==2.5.2
    - Flask==1.1.1
    - fabric==2.5.0
    - Flask-SQLAlchemy==2.4.1
    - Flask-RESTful
    - flask-marshmallow
    - psycopg2-binary
    - pytest==5.4.1
    - SQLAlchemy==1.3.13
    - black==19.10b0
    - flask_script
    - nltk
    - numpy==1.17.5
    - networkx
