"""removed uuid column and renamed string column

Revision ID: 9d643c722603
Revises: d3779ccfbeac
Create Date: 2020-09-26 20:31:28.860511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d643c722603'
down_revision = 'd3779ccfbeac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary', sa.String(), nullable=True))
    op.drop_column('documents', 'string')
    op.drop_column('documents', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('string', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'summary')
    # ### end Alembic commands ###
